{% set version = "3.2.1" %}

package:
  name: podman-py
  version: {{ version }}

source:
  url: https://github.com/containers/podman-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9bb5839af9ada03fe4f1d223162b0de96f71e5387519966b1bd218bf04301df0

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - pyxdg >=0.26
    - setuptools
    - requests >=2.24
    - toml >=0.10.2
    - typing_extensions            # [py<=38]
    - urllib3 >=1.24.2
  run:
    - python
    - pyxdg >=0.26
    - requests >=2.24
    - toml >=0.10.2
    - typing_extensions            # [py<=38]
    - urllib3 >=1.24.2

test:
  imports:
    - podman

about:
  home: https://github.com/containers/podman-py
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python bindings and code examples for using Varlink access to Podman Service
  dev_url: https://github.com/containers/podman-py

extra:
  recipe-maintainers:
    - h-vetinari
    - '4383'
